USE GuildCars1
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = 'FramesSelectAll')
		DROP PROCEDURE DbReset
GO

CREATE PROCEDURE FramesSelectAll AS
BEGIN
	SELECT BikeFrameId, BikeFrame 
	FROM BikeFrameTable
END